apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-access
rules:
- apiGroups: ["*"]  # This allows access to all API groups
  resources: ["*"]   # This allows access to all resources
  verbs: ["*"]       # This allows all actions (get, list, create, delete, etc.)
