apiVersion: v1
kind: Service
metadata:
  name: k8smonitor
  namespace: default
spec:
  selector:
    app: k8smonitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # NodePort to expose (choose an available port)
  type: NodePort
